### ISSUE TITLE
Thread waiting for connection

### ISSUE THREAD

**Issue by vesse** [ptaoussanis/carmine#112]
My server application became unresponsive. Here is the beginning of what `jstack` printed:

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode):

"worker-4" daemon prio=10 tid=0x00007ffa00016000 nid=0x487d waiting on condition [0x00007ffa758f9000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007078d9720> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:524)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:360)
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277)
        at taoensso.carmine.connections.ConnectionPool.get_conn(connections.clj:44)
        at taoensso.carmine.connections$pooled_conn.invoke(connections.clj:167)
```

Redis was up and running and didn't find anything from it's logs. The application has two workers, both with same settings. `pool` and `spec` parameters for the connection are empty, `eoq-backoff-ms` is 1000, and `nthreads` is 2.

Any idea what has gone wrong?

**Comment by gfredericks** [comment]
Could this be caused by #135?
