### ISSUE TITLE
Carmine throws exception on Redis cluster MOVED response

### ISSUE THREAD

**Issue by CVTJNII** [ptaoussanis/carmine#146]
When Carmine is pointed against a cluster it throws an exception when a MOVED response is returned:

```
clojure.lang.ExceptionInfo: MOVED 9102 192.168.253.131:6379 {:prefix :moved}
        at clojure.core$ex_info.invoke(core.clj:4403)
        at taoensso.carmine.protocol$get_unparsed_reply.invoke(protocol.clj:141)
        at taoensso.carmine.protocol$get_parsed_reply.invoke(protocol.clj:203)
        at taoensso.carmine.protocol$execute_requests.invoke(protocol.clj:277)
        at taoensso.carmine.protocol$execute_requests.invoke(protocol.clj:262)
```

This is expected Redis behavior as Redis doesn't proxy requests: http://redis.io/topics/cluster-spec Carmine should follow the MOVED messages to the correct master.

**Comment by ptaoussanis** [comment]
Hi Tom,

Carmine doesn't support Redis Cluster yet. Don't have time to work on this myself atm, but most of the necessary infrastructure is already in place and a PR would be welcome: https://github.com/ptaoussanis/carmine/issues/76

**Comment by CVTJNII** [comment]
Okay, great.  I missed #76 in my search, I'll close this ticket in favor of #76.  Thanks.

**Comment by ptaoussanis** [comment]
No problem :-)
